### ISSUE TITLE
On the weights of network

### ISSUE THREAD

**Issue by chengricky** [liuh127/DW-GAN-Dehazing#1]
Hi. Thanks for your great work.
It seems that the weights of network deposited on Google Drive is not accessible right now. When would the weights be available?

**Comment by liuh127** [comment]
> Hi. Thanks for your great work.
> It seems that the weights of network deposited on Google Drive is not accessible right now. When would the weights be available?

You should be able to access our model weights now.

**Comment by leslieburke** [comment]
@liuh127 hello, Thanks for your great work.
But this download link still doesn't seem to work, can you provide another way to download?

**Comment by xuxingxing-d** [comment]
But this download link still doesn't seem to work, can you provide another way to download?
